package com.estonianport.agendaza.dao

import com.estonianport.agendaza.model.CateringEventoExtraVariableCatering
import org.springframework.data.repository.CrudRepository

interface CateringEventoExtraVariableCateringDao : CrudRepository<CateringEventoExtraVariableCatering, Long>